# Generated by Django 5.2.17 on 2026-09-29 11:00

import chat.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=chat.models.new_chat_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("owner", models.CharField(db_index=True, max_length=80)),
                ("title", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.CharField(max_length=80)),
                ("day", models.DateField()),
                ("used", models.PositiveIntegerField(default=0)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "day"), name="one_budget_per_day"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Access",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visitor", models.CharField(max_length=80)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guests",
                        to="chat.chat",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chat", "visitor"), name="one_access_per_visitor"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq", models.PositiveIntegerField()),
                ("type", models.CharField(max_length=24)),
                ("task", models.CharField(blank=True, default="", max_length=32)),
                ("ref", models.CharField(blank=True, default="", max_length=64)),
                ("payload", models.JSONField()),
                ("created_at", models.BigIntegerField()),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="chat.chat",
                    ),
                ),
            ],
            options={
                "ordering": ["seq"],
                "indexes": [
                    models.Index(fields=["task"], name="chat_event_task_77c22f_idx"),
                    models.Index(fields=["ref"], name="chat_event_ref_b413cc_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chat", "seq"), name="one_event_per_seq"
                    )
                ],
            },
        ),
    ]
