# Generated by Django 6.1.1 on 2026-10-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('redirect_uris', models.JSONField()),
                ('fetched_at', models.BigIntegerField(default=0)),
                ('created_at', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('digest', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=512)),
                ('owner', models.CharField(max_length=80)),
                ('redirect_uri', models.CharField(max_length=2000)),
                ('challenge', models.CharField(max_length=128)),
                ('resource', models.CharField(max_length=300)),
                ('scope', models.CharField(max_length=100)),
                ('expires_at', models.BigIntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('digest', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=8)),
                ('family', models.CharField(db_index=True, max_length=32)),
                ('client_id', models.CharField(max_length=512)),
                ('owner', models.CharField(db_index=True, max_length=80)),
                ('resource', models.CharField(max_length=300)),
                ('scope', models.CharField(max_length=100)),
                ('expires_at', models.BigIntegerField(db_index=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
