// SPDX-License-Identifier: AGPL-3.0-or-later
// Every brand asset as SVG, composed from the traced lettering (design/mark/*.svg, made once by
// design/trace/trace.py), the geometry of the plus and the symbol (design/mark.mjs) and the brand colours of
// design/tokens.json. Nothing here is drawn from a font. `brandFiles` returns the files by path from the
// repository root; design/build.mjs writes them and design/raster.mjs makes the icons' PNGs from them.
import { toHex } from "./color.mjs";
import { ASK, LOGO_BOX, NUMERALS, PLUS, SYMBOL, lockup } from "./mark.mjs";

const GENERATED = "Generated by design/build.mjs from design/tokens.json and design/mark.mjs. Do not edit.";
const SVG_NS = 'xmlns="http://www.w3.org/2000/svg"';
const KEYLINE = 6;

/** The palette of one version of the logo: a fill for the numerals and each of the three pills. */
function palettes(brand) {
  const c = (name) => toHex(brand[name]);
  return {
    colour: { numerals: c("deep"), top: c("green"), right: c("green"), mint: c("mint-soft"), keyline: false },
    reverse: { numerals: c("white"), top: c("vivid"), right: c("vivid"), mint: c("mint"), keyline: false },
    mono: { numerals: c("charcoal"), top: c("charcoal"), right: c("charcoal"), mint: c("charcoal"), keyline: true },
    single: { numerals: c("deep"), top: c("deep"), right: c("deep"), mint: c("deep"), keyline: true },
  };
}

const box = (b) => `${b.x} ${b.y} ${b.width} ${b.height}`;
const svg = (viewBox, inner, extra = "") => `<svg ${SVG_NS} viewBox="${viewBox}"${extra}>${inner}</svg>\n`;
const titled = (title, inner) => `<title>${title}</title>${inner}`;

/**
 * The logo's shapes in paint order. With a keyline (the one-colour versions) each shape is cut back from
 * the ones painted after it, so the pills stay apart from each other and from the 4 without any ground colour.
 */
function logoShapes(p, id = "k") {
  const parts = [
    ["numerals", `<path d="${NUMERALS.d}" fill-rule="evenodd"/>`],
    ["top", `<path d="${PLUS.top}"/>`],
    ["right", `<path d="${PLUS.right}"/>`],
    ["mint", `<path d="${PLUS.mint}"/>`],
  ];
  let defs = "";
  const drawn = parts.map(([name, path], i) => {
    if (!p.keyline || i === parts.length - 1) return path.replace("<path", `<path fill="${p[name]}"`);
    const above = parts.slice(i + 1).filter(([n]) => n !== "numerals").map(([, d]) => d.replace("<path", `<path fill="#000" stroke="#000" stroke-width="${KEYLINE * 2}" stroke-linejoin="round"`));
    defs += `<mask id="${id}-${name}" maskUnits="userSpaceOnUse" x="-20" y="-80" width="1000" height="560"><rect x="-20" y="-80" width="1000" height="560" fill="#fff"/>${above.join("")}</mask>`;
    return `<g mask="url(#${id}-${name})">${path.replace("<path", `<path fill="${p[name]}"`)}</g>`;
  });
  return (defs ? `<defs>${defs}</defs>` : "") + drawn.join("");
}

const logo = (p, title, id) => svg(box(LOGO_BOX), titled(title, logoShapes(p, id)));
const wordmark = (color) =>
  svg(`0 0 ${NUMERALS.width} ${NUMERALS.height}`, titled("234", `<path d="${NUMERALS.d}" fill="${color}" fill-rule="evenodd"/>`));

function lockupSvg(p, askColor, digitColor) {
  const l = lockup();
  const inner =
    logoShapes(p, "kl") +
    `<path transform="${l.ask}" d="${ASK.d}" fill="${askColor}" fill-rule="evenodd"/>` +
    `<path transform="${l.digits}" d="${NUMERALS.d}" fill="${digitColor}" fill-rule="evenodd"/>` +
    `<circle cx="${l.dot.cx.toFixed(1)}" cy="${l.dot.cy.toFixed(1)}" r="${l.dot.r.toFixed(1)}" fill="${digitColor}"/>`;
  return svg(box(l.box), titled("Ask 234.", inner));
}

function symbol(brand) {
  const c = (name) => toHex(brand[name]);
  return svg(
    "0 0 100 100",
    titled(
      "234",
      `<path d="${SYMBOL.top}" fill="${c("bright")}"/><path d="${SYMBOL.left}" fill="${c("mint")}"/><path d="${SYMBOL.right}" fill="${c("vivid")}"/><path d="${SYMBOL.bottom}" fill="${c("deep")}"/>`,
    ),
  );
}

/** The logo placed `fraction` of the tile wide, centred on the tile. */
function placed(size, fraction, p, id) {
  const k = (size * fraction) / LOGO_BOX.width;
  const x = size / 2 - (LOGO_BOX.x + LOGO_BOX.width / 2) * k;
  const y = size / 2 - (LOGO_BOX.y + LOGO_BOX.height / 2) * k;
  return `<g transform="translate(${x.toFixed(2)} ${y.toFixed(2)}) scale(${k.toFixed(5)})">${logoShapes(p, id)}</g>`;
}

const RADIUS = 0.225;
const tile = (size, radius, fill) => `<rect width="${size}" height="${size}" rx="${radius}" fill="${fill}"/>`;

/** The flat app icon: deep green tile, the reverse logo. `full` is a square to the edge (touch and maskable icons). */
function flatIcon(brand, { size = 512, fraction = 0.74, full = false, title = "234" } = {}) {
  const p = palettes(brand).reverse;
  return svg(`0 0 ${size} ${size}`, titled(title, tile(size, full ? 0 : size * RADIUS, toHex(brand.deep)) + placed(size, fraction, p, "kf")), ` width="${size}" height="${size}"`);
}

/** The plus on its own on a deep tile: the favicon and the avatar. */
function plusIcon(brand, size = 512) {
  const p = palettes(brand).reverse;
  const fraction = 0.56;
  const k = (size * fraction) / 183; // the plus is 183 wide (768..951)
  const x = size / 2 - (768 + 183 / 2) * k;
  const y = size / 2 - (-61 + 232 / 2) * k - size * 0.012;
  const plus = `<g transform="translate(${x.toFixed(2)} ${y.toFixed(2)}) scale(${k.toFixed(5)})"><path fill="${p.top}" d="${PLUS.top}"/><path fill="${p.right}" d="${PLUS.right}"/><path fill="${p.mint}" d="${PLUS.mint}"/></g>`;
  return svg(`0 0 ${size} ${size}`, titled("234", tile(size, size * RADIUS, toHex(brand.deep)) + plus), ` width="${size}" height="${size}"`);
}

/** The outlined icon: a pale tile with a deep green edge, the colour logo. */
function outlineIcon(brand, size = 512) {
  const edge = size * 0.032;
  const inset = size * 0.1;
  const side = size - inset * 2;
  const body = `<rect x="${inset + edge / 2}" y="${inset + edge / 2}" width="${side - edge}" height="${side - edge}" rx="${side * RADIUS}" fill="${toHex(brand["mint-soft"])}" fill-opacity=".45" stroke="${toHex(brand.deep)}" stroke-width="${edge}"/>`;
  return svg(`0 0 ${size} ${size}`, titled("234", body + placed(size, 0.6, palettes(brand).colour, "ko")), ` width="${size}" height="${size}"`);
}

/** The icon with depth: a lit green face, a bright rim on the upper left edge, a soft shadow. For marketing and stores. */
function depthIcon(brand, size = 512) {
  const c = (name) => toHex(brand[name]);
  const inset = size * 0.1;
  const side = size - inset * 2;
  const r = side * RADIUS;
  const defs =
    `<defs><linearGradient id="face" x1=".15" y1="0" x2=".85" y2="1"><stop offset="0" stop-color="${c("lift")}"/><stop offset="1" stop-color="${c("shade")}"/></linearGradient>` +
    `<linearGradient id="rim" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${c("rim")}"/><stop offset=".5" stop-color="${c("deep")}"/><stop offset="1" stop-color="${c("shade")}"/></linearGradient>` +
    `<filter id="drop" x="-20%" y="-20%" width="140%" height="150%"><feDropShadow dx="0" dy="${size * 0.02}" stdDeviation="${size * 0.025}" flood-color="${c("shade")}" flood-opacity=".55"/></filter>` +
    `<filter id="lift" x="-5%" y="-5%" width="110%" height="115%"><feDropShadow dx="0" dy="${size * 0.008}" stdDeviation="${size * 0.006}" flood-color="${c("shade")}" flood-opacity=".6"/></filter></defs>`;
  const face =
    `<rect x="${inset}" y="${inset}" width="${side}" height="${side}" rx="${r}" fill="url(#rim)" filter="url(#drop)"/>` +
    `<rect x="${inset + size * 0.012}" y="${inset + size * 0.012}" width="${side - size * 0.024}" height="${side - size * 0.024}" rx="${r - size * 0.012}" fill="url(#face)"/>`;
  const mark = `<g filter="url(#lift)">${placed(size, 0.62, palettes(brand).reverse, "kd")}</g>`;
  return svg(`0 0 ${size} ${size}`, titled("234", defs + face + mark), ` width="${size}" height="${size}"`);
}

const BRAND_DIR = "host/src/chat/static/chat/brand/";

/** The home's wordmark: the colour logo in the theme's own colours, for a partial the chat page includes. */
export function wordmarkPartial() {
  return (
    `{# ${GENERATED} #}\n` +
    `<svg viewBox="${box(LOGO_BOX)}" class="h-24 w-auto overflow-visible" aria-hidden="true">` +
    `<path class="fill-mark" fill-rule="evenodd" d="${NUMERALS.d}"/>` +
    `<path class="fill-accent" d="${PLUS.top}"/><path class="fill-accent" d="${PLUS.right}"/><path class="fill-mark-mint" d="${PLUS.mint}"/></svg>\n`
  );
}

export function brandFiles(tokens) {
  const { brand } = tokens;
  const p = palettes(brand);
  const c = (name) => toHex(brand[name]);
  const files = {
    "logo.svg": logo(p.colour, "234", "k"),
    "logo-mono.svg": logo(p.mono, "234", "k"),
    "logo-reverse.svg": logo(p.reverse, "234", "k"),
    "logo-single.svg": logo(p.single, "234", "k"),
    "lockup.svg": lockupSvg(p.colour, c("charcoal"), c("deep")),
    "lockup-reverse.svg": lockupSvg(p.reverse, c("white"), c("white")),
    "symbol.svg": symbol(brand),
    "wordmark.svg": wordmark(c("deep")),
    "wordmark-reverse.svg": wordmark(c("white")),
    "app-icon-flat.svg": flatIcon(brand),
    "app-icon-outline.svg": outlineIcon(brand),
    "app-icon-depth.svg": depthIcon(brand),
    "favicon.svg": plusIcon(brand),
  };
  const out = Object.fromEntries(Object.entries(files).map(([name, text]) => [`design/brand/${name}`, text]));
  out[`${BRAND_DIR}favicon.svg`] = files["favicon.svg"];
  out[`${BRAND_DIR}icon.svg`] = flatIcon(brand, { fraction: 0.74 });
  out[`${BRAND_DIR}icon-maskable.svg`] = flatIcon(brand, { fraction: 0.66, full: true });
  out["host/src/chat/templates/chat/_wordmark.html"] = wordmarkPartial();
  return out;
}
