// SPDX-License-Identifier: AGPL-3.0-or-later
// Generates everything that carries the design tokens, from tokens.json alone:
//   design/generated/tokens.css   custom properties for both themes (a stylesheet imports it)
//   design/generated/theme.css    the same names as Tailwind utilities (bg-ground, text-ink-2, rounded-card)
//   checkout/src/checkout/tokens_css.py   the properties as a string, for the simulated checkout page
//   host/src/chat/palette.py      the ground colour of each theme and the primary, for the manifest and the browser's theme colour
//   host/src/chat/static/chat/host-styles.js   the theme in the names ext-apps gives a view, for hostContext.styles
//   the brand assets as SVG (design/brand/*.svg), the home's wordmark partial and the icons' SVG sources
//   (design/brand.mjs); the icons' PNGs are made by design/raster.mjs
// usage: node design/build.mjs [--check]   (--check writes nothing and exits 1 when a committed file is out of date)
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { brandFiles } from "./brand.mjs";
import { toHex } from "./color.mjs";
import { hostStyleVariables } from "./host-styles.mjs";
import { loadTokens } from "./tokens.mjs";

const root = new URL("..", import.meta.url).pathname;
const tokens = loadTokens();
const hexes = (colors) => Object.entries(colors).map(([name, value]) => [name, toHex(value)]);
const declare = (pairs, indent = "  ") => pairs.map(([name, value]) => `${indent}--${name}: ${value.replaceAll(", ", `,\n${indent}  `)};`).join("\n");

const light = hexes(tokens.colors.light);
const dark = hexes(tokens.colors.dark);
const shape = Object.entries(tokens.shape);
const type = Object.entries(tokens.type);

export const tokensCss = `${[
  `:root {\n  color-scheme: light dark;\n${declare([...light, ...shape, ...type])}\n}`,
  `@media (prefers-color-scheme: dark) {\n  :root {\n${declare(dark, "    ")}\n  }\n}`,
  `:root.light {\n  color-scheme: light;\n${declare(light)}\n}`,
  `:root.dark {\n  color-scheme: dark;\n${declare(dark)}\n}`,
].join("\n")}\n`;

const utilities = [
  "--color-*: initial;",
  ...light.map(([name]) => `--color-${name}: var(--${name});`),
  ...shape.map(([name]) => `--radius-${name.slice(2)}: var(--${name});`),
  "--shadow-soft: 0 1px 2px var(--shadow), 0 8px 24px -8px var(--shadow);",
  "--font-sans: var(--stack-sans);",
  "--font-display: var(--stack-display);",
];
export const themeCss = `@theme inline {\n  ${utilities.join("\n  ")}\n}\n`;

const generated = '"""Generated by design/build.mjs from design/tokens.json. Do not edit."""\n\n';
const faviconUri = `data:image/svg+xml;base64,${Buffer.from(brandFiles(tokens)["design/brand/favicon.svg"]).toString("base64")}`;
// The data URI is emitted as adjacent string literals of at most 100 characters, so the file passes the checkout's line limit.
const pythonLiterals = (text, width = 100) => (text.match(new RegExp(`.{1,${width}}`, "gs")) ?? []).map((part) => `    "${part}"`).join("\n");
export const checkoutPy = `${generated}TOKENS_CSS = """\\\n${tokensCss}"""\n\nFAVICON_URI = (\n${pythonLiterals(faviconUri)}\n)\n`;
const ground = ["light", "dark"].map((theme) => `"${theme}": "${toHex(tokens.colors[theme].ground)}"`);
export const paletteMap = `${generated}GROUND = {${ground.join(", ")}}\nPRIMARY = "${toHex(tokens.colors.light.primary)}"\n`;

export const hostStylesJs = `// Generated by design/build.mjs from design/tokens.json. Do not edit.\nexport const HOST_STYLE_VARIABLES = ${JSON.stringify(hostStyleVariables(tokens), null, 2)};\n`;

const outputs = {
  "design/generated/tokens.css": tokensCss,
  "design/generated/theme.css": themeCss,
  "checkout/src/checkout/tokens_css.py": checkoutPy,
  "host/src/chat/palette.py": paletteMap,
  "host/src/chat/static/chat/host-styles.js": hostStylesJs,
  ...brandFiles(tokens),
};

// A file that is already right is left alone: the Workers dev server rebuilds whenever a source file changes.
function isCurrent(path, text) {
  try {
    return readFileSync(`${root}${path}`, "utf8") === text;
  } catch {
    return false;
  }
}

if (process.argv[1] === new URL(import.meta.url).pathname) {
  const check = process.argv.includes("--check");
  let stale = 0;
  mkdirSync(`${root}design/generated`, { recursive: true });
  for (const [path, text] of Object.entries(outputs)) {
    if (check) {
      // design/generated/ holds build intermediates that git ignores: only the committed outputs are checked.
      if (!path.startsWith("design/generated/") && !isCurrent(path, text)) { console.log(`out of date: ${path}`); stale += 1; }
    } else if (!isCurrent(path, text)) {
      mkdirSync(dirname(`${root}${path}`), { recursive: true });
      writeFileSync(`${root}${path}`, text);
    }
  }
  process.exit(stale ? 1 : 0);
}
