"""Generated by design/build.mjs from design/tokens.json. Do not edit."""

TOKENS_CSS = """\
:root {
  color-scheme: light dark;
  --ground: #faf8f2;
  --raised: #fefdfa;
  --sunken: #f0ede4;
  --mint: #e0f7ea;
  --line: #dedad1;
  --line-strong: #8e897c;
  --ink: #221f18;
  --ink-2: #535046;
  --ink-3: #66635a;
  --primary: #03492f;
  --primary-hover: #023924;
  --primary-pressed: #022b1a;
  --on-primary: #fdfcf7;
  --accent: #00ad53;
  --mark: #03492f;
  --mark-mint: #ddf3e6;
  --ok: #005f5f;
  --ok-soft: #ddf6f6;
  --warn: #7b4c00;
  --warn-soft: #fdefcb;
  --bad: #b31415;
  --bad-soft: #fee9e8;
  --scrim: #0e191373;
  --shadow: #091a1114;
  --tile-main: #cff6e0;
  --tile-main-ink: #0c4f33;
  --tile-soup: #fee6d4;
  --tile-soup-ink: #753b07;
  --tile-side: #e9f1c3;
  --tile-side-ink: #424e08;
  --tile-drink: #d3f1fd;
  --tile-drink-ink: #04526d;
  --google-surface: #ffffff;
  --google-edge: #747775;
  --google-ink: #1f1f1f;
  --r-control: .75rem;
  --r-card: 1rem;
  --r-sheet: 1.25rem;
  --stack-sans: system-ui,
    -apple-system,
    "Segoe UI",
    Roboto,
    "Helvetica Neue",
    Arial,
    "Noto Sans",
    sans-serif;
  --stack-display: Manrope,
    system-ui,
    -apple-system,
    "Segoe UI",
    Roboto,
    sans-serif;
}
@media (prefers-color-scheme: dark) {
  :root {
    --ground: #08120c;
    --raised: #0e1d15;
    --sunken: #17291f;
    --mint: #143525;
    --line: #283a30;
    --line-strong: #668272;
    --ink: #e6f3e8;
    --ink-2: #afc4b5;
    --ink-3: #97aa9c;
    --primary: #38d080;
    --primary-hover: #5adf92;
    --primary-pressed: #2bbb71;
    --on-primary: #001a0c;
    --accent: #01d879;
    --mark: #fefdfe;
    --mark-mint: #cbfae3;
    --ok: #57d4d4;
    --ok-soft: #012d2d;
    --warn: #e8be62;
    --warn-soft: #322405;
    --bad: #ff9689;
    --bad-soft: #3b1c1b;
    --scrim: #00030199;
    --shadow: #00000059;
    --tile-main: #073421;
    --tile-main-ink: #95e6bb;
    --tile-soup: #3d250f;
    --tile-soup-ink: #fdc495;
    --tile-side: #2b2e0e;
    --tile-side-ink: #cbd689;
    --tile-drink: #122f3a;
    --tile-drink-ink: #93d9f5;
    --google-surface: #131314;
    --google-edge: #8e918f;
    --google-ink: #e3e3e3;
  }
}
:root.light {
  color-scheme: light;
  --ground: #faf8f2;
  --raised: #fefdfa;
  --sunken: #f0ede4;
  --mint: #e0f7ea;
  --line: #dedad1;
  --line-strong: #8e897c;
  --ink: #221f18;
  --ink-2: #535046;
  --ink-3: #66635a;
  --primary: #03492f;
  --primary-hover: #023924;
  --primary-pressed: #022b1a;
  --on-primary: #fdfcf7;
  --accent: #00ad53;
  --mark: #03492f;
  --mark-mint: #ddf3e6;
  --ok: #005f5f;
  --ok-soft: #ddf6f6;
  --warn: #7b4c00;
  --warn-soft: #fdefcb;
  --bad: #b31415;
  --bad-soft: #fee9e8;
  --scrim: #0e191373;
  --shadow: #091a1114;
  --tile-main: #cff6e0;
  --tile-main-ink: #0c4f33;
  --tile-soup: #fee6d4;
  --tile-soup-ink: #753b07;
  --tile-side: #e9f1c3;
  --tile-side-ink: #424e08;
  --tile-drink: #d3f1fd;
  --tile-drink-ink: #04526d;
  --google-surface: #ffffff;
  --google-edge: #747775;
  --google-ink: #1f1f1f;
}
:root.dark {
  color-scheme: dark;
  --ground: #08120c;
  --raised: #0e1d15;
  --sunken: #17291f;
  --mint: #143525;
  --line: #283a30;
  --line-strong: #668272;
  --ink: #e6f3e8;
  --ink-2: #afc4b5;
  --ink-3: #97aa9c;
  --primary: #38d080;
  --primary-hover: #5adf92;
  --primary-pressed: #2bbb71;
  --on-primary: #001a0c;
  --accent: #01d879;
  --mark: #fefdfe;
  --mark-mint: #cbfae3;
  --ok: #57d4d4;
  --ok-soft: #012d2d;
  --warn: #e8be62;
  --warn-soft: #322405;
  --bad: #ff9689;
  --bad-soft: #3b1c1b;
  --scrim: #00030199;
  --shadow: #00000059;
  --tile-main: #073421;
  --tile-main-ink: #95e6bb;
  --tile-soup: #3d250f;
  --tile-soup-ink: #fdc495;
  --tile-side: #2b2e0e;
  --tile-side-ink: #cbd689;
  --tile-drink: #122f3a;
  --tile-drink-ink: #93d9f5;
  --google-surface: #131314;
  --google-edge: #8e918f;
  --google-ink: #e3e3e3;
}
"""

FAVICON_URI = (
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1MT"
    "IgNTEyIiB3aWR0aD0iNTEyIiBoZWlnaHQ9IjUxMiI+PHRpdGxlPjIzNDwvdGl0bGU+PHJlY3Qgd2lkdGg9IjUxMiIgaGVpZ2h0PS"
    "I1MTIiIHJ4PSIxMTUuMiIgZmlsbD0iIzAzNDkyZiIvPjxnIHRyYW5zZm9ybT0idHJhbnNsYXRlKC0xMDkwLjY0IDE2My42OCkgc2"
    "NhbGUoMS41NjY3OCkiPjxwYXRoIGZpbGw9IiMwMWQ4NzkiIGQ9Ik04NTggMjlWLTE2QTQ1IDQ1IDAgMCAwIDc2OCAtMTZBNDUgND"
    "UgMCAwIDAgODEzIDI5WiIvPjxwYXRoIGZpbGw9IiMwMWQ4NzkiIGQ9Ik04NTggMjRIOTAzQTQ4IDQ4IDAgMCAxIDkwMyAxMjBIOD"
    "U4WiIvPjxwYXRoIGZpbGw9IiNjYmZhZTMiIGQ9Ik03NjggMjRIODU4VjEyNkE0NSA0NSAwIDAgMSA3NjggMTI2WiIvPjwvZz48L3"
    "N2Zz4K"
)
