#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Puts the licence header on the repository's own .py, .js, .mjs and .sh files, or checks that they have it.

usage: tools/spdx.py            add the header where it is missing
       tools/spdx.py --check    list the files without it and exit 1 (the CI runs this)

Only files git tracks are looked at. Vendored code, generated files and empty files are left alone.
"""

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LICENCE = "AGPL-3.0-or-later"
COMMENT = {".py": "#", ".sh": "#", ".js": "//", ".mjs": "//"}
SKIPPED_PARTS = ("/vendor/", "/node_modules/", "/python_modules/")
SKIPPED_PREFIXES = ("reference/", ".internal/", "design/generated/")
GENERATED_MARKERS = ("Generated by design/build.mjs", "Generated by Django")


def tracked() -> list[Path]:
    names = subprocess.run(
        ["git", "ls-files", "-z"], cwd=ROOT, check=True, capture_output=True, text=True
    ).stdout.split("\0")
    return [ROOT / n for n in names if n and Path(n).suffix in COMMENT]


def is_first_party(path: Path) -> bool:
    rel = "/" + path.relative_to(ROOT).as_posix()
    if any(part in rel for part in SKIPPED_PARTS) or rel[1:].startswith(SKIPPED_PREFIXES):
        return False
    if not path.is_file() or path.stat().st_size == 0:
        return False
    head = "".join(path.read_text(encoding="utf-8").splitlines(keepends=True)[:3])
    return not any(marker in head for marker in GENERATED_MARKERS)


def has_header(text: str) -> bool:
    return f"SPDX-License-Identifier: {LICENCE}" in "".join(text.splitlines(keepends=True)[:3])


def with_header(path: Path, text: str) -> str:
    line = f"{COMMENT[path.suffix]} SPDX-License-Identifier: {LICENCE}\n"
    lines = text.splitlines(keepends=True)
    at = 1 if lines and lines[0].startswith("#!") else 0
    return "".join(lines[:at]) + line + "".join(lines[at:])


def main(check: bool) -> int:
    missing = []
    for path in filter(is_first_party, tracked()):
        text = path.read_text(encoding="utf-8")
        if has_header(text):
            continue
        missing.append(path.relative_to(ROOT).as_posix())
        if not check:
            path.write_text(with_header(path, text), encoding="utf-8")
    if check and missing:
        print("No SPDX header (run tools/spdx.py):", *missing, sep="\n  ")
    elif missing:
        print(f"Added the header to {len(missing)} files.")
    return 1 if check and missing else 0


if __name__ == "__main__":
    sys.exit(main("--check" in sys.argv[1:]))
