# SPDX-License-Identifier: AGPL-3.0-or-later
"""Paystack's list of Nigerian banks: `GET /bank?country=nigeria`, fetched once on 2026-09-30 with a test key.

Public data, kept as Python so the Worker bundles it with the code. Each row is (name, code, slug, type),
in the order Paystack returned them; names have their spaces tidied. One row is left out: the USD entry
of Zenith Bank, which has the same code 057 as its NGN entry. Several banks share a code (BANKIT,
Kolomoni, U and C, Stellas and YCT, Goodnews and Prospa): the first row of a code is the name shown for it.
"""

BANK_LIST: tuple[tuple[str, str, str, str], ...] = (
    ("5TT MFB", "51455", "5tt-mfb-ng", "nuban"),
    ("78 Finance Company Ltd", "40195", "78-finance-company-ltd-ng", "nuban"),
    ("9jaPay Microfinance Bank", "090629", "9japay-microfinance-bank-ng", "nuban"),
    ("9mobile 9Payment Service Bank", "120001", "9mobile-9payment-service-bank-ng", "nuban"),
    ("Abbey Mortgage Bank", "404", "abbey-mortgage-bank-ng", "nuban"),
    ("Above Only MFB", "51204", "above-only-mfb", "nuban"),
    ("Abulesoro MFB", "51312", "abulesoro-mfb-ng", "nuban"),
    ("Access Bank", "044", "access-bank", "nuban"),
    ("Access Bank (Diamond)", "063", "access-bank-diamond", "nuban"),
    ("Accion Microfinance Bank", "602", "accion-microfinance-bank-ng", "nuban"),
    ("Adamawa Mortgage Bank Limited", "90102", "adamawa-mortgage-bank-limited-ng", "nuban"),
    ("Advancly MFB", "090759", "advancly-mfb-ng", "nuban"),
    ("Aella MFB", "50315", "aella-mfb-ng", "nuban"),
    ("AG Mortgage Bank", "90077", "ag-mortgage-bank-ng", "nuban"),
    (
        "Ahmadu Bello University Microfinance Bank",
        "50036",
        "ahmadu-bello-university-microfinance-bank-ng",
        "nuban",
    ),
    ("Airtel Smartcash PSB", "120004", "airtel-smartcash-psb-ng", "nuban"),
    ("AKU Microfinance Bank", "51336", "aku-mfb", "nuban"),
    ("Akuchukwu Microfinance Bank Limited", "090561", "akuchukwu-microfinance-bank-limited-ng", "nuban"),
    ("Al-Barakah Microfinance Bank", "50055", "al-barakah-microfinance-bank-ng", "nuban"),
    ("ALAT by WEMA", "035A", "alat-by-wema", "nuban"),
    ("Alert MFB", "51074", "alert-mfb-ng", "nuban"),
    ("ALLWORKERS MFB", "50059", "allworkers-mfb-ng", "nuban"),
    ("Alpha Morgan Bank", "108", "alpha-morgan", "nuban"),
    ("Alternative bank", "000304", "the-alternative-bank-ng", "nuban"),
    ("Amju Unique MFB", "50926", "amju-unique-mfb", "nuban"),
    ("Aramoko MFB", "50083", "aramoko-mfb", "nuban"),
    ("ASO Savings and Loans", "401", "asosavings", "nuban"),
    ("ASSET MATRIX MFB", "90287", "asset-matrix-mfb-ng", "nuban"),
    ("Assets Microfinance Bank", "50092", "assets-microfinance-bank-ng", "nuban"),
    ("Astrapolaris MFB LTD", "MFB50094", "astrapolaris-mfb", "nuban"),
    ("ATBU MFB", "90451", "atbu-mfb-ng", "nuban"),
    ("AVUENEGBE MICROFINANCE BANK", "090478", "avuenegbe-microfinance-bank-ng", "nuban"),
    ("AWACASH MICROFINANCE BANK", "51351", "awacash-microfinance-bank-ng", "nuban"),
    ("AZTEC MICROFINANCE BANK LIMITED", "51337", "aztec-microfinance-bank-limited-ng", "nuban"),
    ("Bainescredit MFB", "51229", "bainescredit-mfb", "nuban"),
    ("Banc Corp Microfinance Bank", "50117", "banc-corp-microfinance-bank-ng", "nuban"),
    ("BANK OF AGRICULTURE", "90367", "bank-of-agriculture-ng", "nuban"),
    ("Bank78 Microfinance Bank", "11072", "bank78-microfinance-bank-ng", "nuban"),
    ("BANKIT MFB", "50572", "bankit-mfb-ng", "nuban"),
    ("BANKIT MICROFINANCE BANK LTD", "50572", "bankit-microfinance-bank-ltd-ng", "nuban"),
    ("BANKLY MFB", "51341", "ampersand-microfinance-bank-ng", "nuban"),
    ("Baobab Microfinance Bank", "MFB50992", "baobab-microfinance-bank-ng", "nuban"),
    ("BC Kash Microfinance Bank", "51212", "bc-kash-microfinance-bank-ng", "nuban"),
    ("BellBank Microfinance Bank", "51100", "bellbank-microfinance-bank-ng", "nuban"),
    ("Benysta Microfinance Bank Limited", "51267", "benysta-microfinance-bank-limited", "nuban"),
    ("Berachah Microfinance Bank Ltd.", "50122", "berachah-microfinance-bank-ltd-ng", "nuban"),
    ("Beststar Microfinance Bank", "50123", "beststar-microfinance-bank-ng", "nuban"),
    ("BLOC MFB", "51411", "bloc-mfb-ng", "nuban"),
    ("BOLD MFB", "50725", "bold-mfb-ng", "nuban"),
    ("Boost Microfinance Bank", "51449", "boost-microfinance-bank-ng", "nuban"),
    ("Bosak Microfinance Bank", "650", "bosak-microfinance-bank-ng", "nuban"),
    ("Bowen Microfinance Bank", "50931", "bowen-microfinance-bank", "nuban"),
    ("Branch International Finance Company Limited", "FC40163", "branch", "nuban"),
    ("Brent Mortgage bank", "90070", "brent-mortgage-bank-ng", "nuban"),
    ("BuyPower MFB", "50645", "buypower-mfb-ng", "nuban"),
    ("BWAY MFB", "90774", "bway-mfb-ng", "nuban"),
    ("Carbon", "565", "carbon", "nuban"),
    ("Cashbridge Microfinance Bank Limited", "51353", "cashbridge-mfb-ng", "nuban"),
    ("CASHCONNECT MFB", "865", "cashconnect-mfb-ng", "nuban"),
    ("Cedrus MFB", "51437", "cedrus-mfb-ng", "nuban"),
    ("CEMCS Microfinance Bank", "50823", "cemcs-microfinance-bank", "nuban"),
    ("Centrum Finance", "050032", "centrum-finance-ng", "nuban"),
    ("CHAMS MOBILE MFB", "100036", "chams-mobile-mfb-ng", "nuban"),
    ("Chanelle Microfinance Bank Limited", "50171", "chanelle-microfinance-bank-limited-ng", "nuban"),
    ("Chikum Microfinance bank", "312", "chikum-microfinance-bank-ng", "nuban"),
    ("Citibank Nigeria", "023", "citibank-nigeria", "nuban"),
    ("CITYCODE MORTAGE BANK", "070027", "citycode-mortage-bank-ng", "nuban"),
    ("Civic Microfinance Bank Limited", "50186", "civic-microfinance-bank-limited-ng", "nuban"),
    ("Consumer Microfinance Bank", "50910", "consumer-microfinance-bank-ng", "nuban"),
    ("Cool Microfinance Bank Limited", "51458", "cool-microfinance-bank-limited-ng", "nuban"),
    ("Cooperative Mortgage Bank", "90089", "cooperative-mortgage-bank-ng", "nuban"),
    ("Corestep MFB", "50204", "corestep-mfb", "nuban"),
    ("Coronation Merchant Bank", "559", "coronation-merchant-bank-ng", "nuban"),
    ("County Finance Limited", "FC40128", "county-finance-limited", "nuban"),
    ("Credit Direct Limited", "40119", "credit-direct-limited-ng", "nuban"),
    ("Crescent MFB", "51297", "crescent-mfb", "nuban"),
    ("Crust Microfinance Bank", "090560", "crust-microfinance-bank-ng", "nuban"),
    ("CRUTECH MICROFINANCE BANK LTD", "50216", "crutech-microfinance-bank-ltd-ng", "nuban"),
    ("Dash Microfinance Bank", "51368", "dash-microfinance-bank-ng", "nuban"),
    ("Davenport MICROFINANCE BANK", "51334", "davenport-microfinance-bank-ng", "nuban"),
    ("Dillon Microfinance Bank", "51450", "dillon-microfinance-bank-ng", "nuban"),
    ("Dot Microfinance Bank", "50162", "dot-microfinance-bank-ng", "nuban"),
    ("EBSU Microfinance Bank", "50922", "ebsu-microfinance-bank-ng", "nuban"),
    ("Ecobank Nigeria", "050", "ecobank-nigeria", "nuban"),
    ("Ekimogun MFB", "50263", "ekimogun-mfb-ng", "nuban"),
    ("Ekondo Microfinance Bank", "098", "ekondo-microfinance-bank-ng", "nuban"),
    ("ESO-E MICROFINANCE BANK LIMITED", "50280", "eso-e-microfinance-bank-limited-ng", "nuban"),
    ("Ethica MFB", "51475", "ethica-mfb-ng", "nuban"),
    ("EXCEL FINANCE BANK", "090678", "excel-finance-bank-ng", "nuban"),
    ("Eyowo", "50126", "eyowo", "nuban"),
    ("Fairmoney Microfinance Bank", "51318", "fairmoney-microfinance-bank-ng", "nuban"),
    ("FCMB MFB", "51241", "fcmb-mfb-ng", "nuban"),
    ("Fedeth MFB", "50298", "fedeth-mfb-ng", "nuban"),
    ("Fewchore Finance Company Limited", "050002", "fewchore-finance-company-limited-ng", "nuban"),
    ("FFS Microfinance Bank", "51110", "ffs-microfinance-bank-ng", "nuban"),
    ("Fidelity Bank", "070", "fidelity-bank", "nuban"),
    ("Firmus MFB", "51314", "firmus-mfb", "nuban"),
    ("First Bank of Nigeria", "011", "first-bank-of-nigeria", "nuban"),
    ("First City Monument Bank", "214", "first-city-monument-bank", "nuban"),
    ("First Option MFB", "50934", "first-option-mfb-ng", "nuban"),
    ("FIRST ROYAL MICROFINANCE BANK", "090164", "first-royal-microfinance-bank-ng", "nuban"),
    ("FIRSTMIDAS MFB", "51333", "firstmidas-mfb-ng", "nuban"),
    ("FirstTrust Mortgage Bank Nigeria", "413", "firsttrust-mortgage-bank-nigeria-ng", "nuban"),
    ("Flutterwave MFB", "090567", "flutterwave-mfb-ng", "nuban"),
    ("Fortress MFB", "D53", "fortress-mfb-ng", "nuban"),
    ("FSDH Merchant Bank Limited", "501", "fsdh-merchant-bank-limited", "nuban"),
    ("FUTMINNA MICROFINANCE BANK", "832", "futminna-microfinance-bank-ng", "nuban"),
    ("Garun Mallam MFB", "MFB51093", "garun-mallam-mfb-ng", "nuban"),
    ("Gateway Mortgage Bank LTD", "812", "gateway-mortgage-bank", "nuban"),
    ("Globus Bank", "00103", "globus-bank", "nuban"),
    ("GLORY MFB", "90278", "glory-mfb-ng", "nuban"),
    ("Goldman MFB", "090574", "goldman-mfb-ng", "nuban"),
    ("GOMBE MFB", "90586", "gombe-mfb-ng", "nuban"),
    ("GoMoney", "100022", "gomoney", "nuban"),
    ("GOOD SHEPHERD MICROFINANCE BANK", "090664", "good-shepherd-microfinance-bank-ng", "nuban"),
    ("Goodnews Microfinance Bank", "50739", "goodnews-microfinance-bank-ng", "nuban"),
    ("GRANTS MFB", "90335", "grants-mfb-ng", "nuban"),
    ("Greenwich Merchant Bank", "562", "greenwich-merchant-bank-ng", "nuban"),
    ("GROOMING MICROFINANCE BANK", "51276", "grooming-microfinance-bank-ng", "nuban"),
    ("GTI MFB", "50368", "gti-mfb-ng", "nuban"),
    ("Guaranty Trust Bank", "058", "guaranty-trust-bank", "nuban"),
    ("Hackman Microfinance Bank", "51251", "hackman-microfinance-bank", "nuban"),
    ("Haggai Mortgage Bank", "90065", "haggai-mortgage-bank-ng", "nuban"),
    ("Hasal Microfinance Bank", "50383", "hasal-microfinance-bank", "nuban"),
    ("Hayat Trust MFB", "51364", "hayat-trust-mfb-ng", "nuban"),
    ("HopePSB", "120002", "hopepsb-ng", "nuban"),
    ("IBANK Microfinance Bank", "51211", "IBANK-mfb", "nuban"),
    ("IBBU MFB", "51279", "ibbu-mfb-ng", "nuban"),
    ("Ibile Microfinance Bank", "51244", "ibile-mfb", "nuban"),
    ("Ibom Mortgage Bank", "90012", "ibom-mortgage-bank-ng", "nuban"),
    ("Ikoyi Osun MFB", "50439", "ikoyi-osun-mfb", "nuban"),
    ("Ilaro Poly Microfinance Bank", "50442", "ilaro-poly-microfinance-bank-ng", "nuban"),
    ("Imowo MFB", "50453", "imowo-mfb-ng", "nuban"),
    ("IMPERIAL HOMES MORTAGE BANK", "415", "imperial-homes-mortage-bank-ng", "nuban"),
    ("INEBA GOGO MFB", "51462", "ineba-gogo-mfb-ng", "nuban"),
    ("Infinity MFB", "50457", "infinity-mfb", "nuban"),
    ("Infinity trust Mortgage Bank", "070016", "infinity-trust-mortgage-bank-ng", "nuban"),
    ("ISUA MFB", "090701", "isua-mfb-ng", "nuban"),
    ("Jaiz Bank", "301", "jaiz-bank", "nuban"),
    ("Jubilee Life Mortgage Bank", "402", "jubilee-life-mortgage-bank-ng", "nuban"),
    ("Kadpoly MFB", "50502", "kadpoly-mfb", "nuban"),
    ("KANOPOLY MFB", "51308", "kanopoly-mfb-ng", "nuban"),
    ("KAYI MFB", "90667", "kayi-mfb-ng", "nuban"),
    ("Kayvee Microfinance Bank", "5129", "kayvee-microfinance-bank-ng", "nuban"),
    ("Kebbi Homes Savings and Loans Limited", "90028", "kebbi-homes-savings-and-loans-limited-ng", "nuban"),
    ("Keystone Bank", "082", "keystone-bank", "nuban"),
    ("Kolomoni MFB", "899", "kolomoni-mfb-ng", "nuban"),
    ("Kolomoni Microfinance Bank", "100025", "kolomoni-microfinance-bank-ng", "nuban"),
    ("KONGAPAY (Kongapay Technologies Limited)(formerly Zinternet)", "100025", "kongapay-tech-ltd", "nuban"),
    ("Kredi Money MFB LTD", "50200", "kredi-money-mfb", "nuban"),
    ("Kuda Bank", "50211", "kuda-bank", "nuban"),
    ("Lagos Building Investment Company Plc.", "90052", "lbic-plc", "nuban"),
    ("Lemmy MFB", "091003", "lemmy-mfb-ng", "nuban"),
    ("Letshego Microfinance Bank", "090420", "letshego-microfinance-bank", "nuban"),
    ("Links MFB", "50549", "links-mfb", "nuban"),
    ("Living Trust Mortgage Bank", "031", "living-trust-mortgage-bank", "nuban"),
    ("LOMA MFB", "50491", "loma-mfb-ng", "nuban"),
    ("Lotus Bank", "303", "lotus-bank", "nuban"),
    ("Maal MFB", "51444", "maal-mfb-ng", "nuban"),
    ("MAHFUZ MFB", "90825", "mahfuz-mfb-ng", "nuban"),
    ("MAINSTREET MICROFINANCE BANK", "090171", "mainstreet-microfinance-bank-ng", "nuban"),
    ("Mayden Microfinance Bank", "51474", "mayden-microfinance-bank-ng", "nuban"),
    ("Mayfair MFB", "50563", "mayfair-mfb", "nuban"),
    ("Mayfresh Mortgage Bank", "90003", "mayfresh-mortgage-bank-ng", "nuban"),
    ("Mega Microfinance Bank", "50570", "mega-microfinance-bank-ng", "nuban"),
    (
        "Michael Okpara UniAgric Microfinance Bank",
        "MFB51116M",
        "michael-okpara-uniagric-microfinance-bank-ng",
        "nuban",
    ),
    ("Mint MFB", "50304", "mint-mfb", "nuban"),
    ("MINT-FINEX MFB", "09", "mint-finex-mfb-ng", "nuban"),
    ("Money Master PSB", "946", "money-master-psb-ng", "nuban"),
    ("Moniepoint MFB", "50515", "moniepoint-mfb-ng", "nuban"),
    ("MOVASCO MFB", "90979", "movasco-mfb-ng", "nuban"),
    ("MTN Momo PSB", "120003", "mtn-momo-psb-ng", "nuban"),
    ("MUTUAL BENEFITS MICROFINANCE BANK", "090190", "mutual-benefits-microfinance-bank-ng", "nuban"),
    ("NDCC MICROFINANCE BANK", "090679", "ndcc-microfinance-bank-ng", "nuban"),
    ("NET MICROFINANCE BANK", "51361", "net-microfinance-bank-ng", "nuban"),
    (
        "Nigerian Navy Microfinance Bank Limited",
        "51142",
        "nigerian-navy-microfinance-bank-limited-ng",
        "nuban",
    ),
    ("NIRSAL MICROFINANCE", "51304", "nirsal-microfinance-ng", "nuban"),
    ("Nombank MFB", "50072", "nombank-mfb-ng", "nuban"),
    ("NOVA BANK", "561", "nova-bank-ng", "nuban"),
    ("Novus MFB", "51371", "novus-mfb-ng", "nuban"),
    ("NPF MICROFINANCE BANK", "50629", "npf-microfinance-bank-ng", "nuban"),
    ("NSUK MICROFINANACE BANK", "51261", "nsuk-microfinanace-bank-ng", "nuban"),
    ("NUVION MFB", "51392", "nuvion-mfb-ng", "nuban"),
    (
        "Olabisi Onabanjo University Microfinance Bank",
        "50689",
        "olabisi-onabanjo-university-microfinance-bank-ng",
        "nuban",
    ),
    ("OLUCHUKWU MICROFINANCE BANK LTD", "50697", "oluchukwu-microfinance-bank-ltd-ng", "nuban"),
    ("OPay Digital Services Limited (OPay)", "999992", "paycom", "nuban"),
    ("Optimus Bank Limited", "107", "optimus-bank-ltd", "nuban"),
    ("Pact Microfinance Bank", "51477", "pact-microfinance-bank-ng", "nuban"),
    ("Paga", "100002", "paga", "nuban"),
    ("PalmPay", "999991", "palmpay", "nuban"),
    ("Parallex Bank", "104", "parallex-bank", "nuban"),
    ("Parkway - ReadyCash", "311", "parkway-ready-cash", "nuban"),
    ("PATHFINDER MICROFINANCE BANK LIMITED", "090680", "pathfinder-microfinance-bank-limited-ng", "nuban"),
    ("PATRICKGOLD MFB", "90317", "patrickgold-mfb-ng", "nuban"),
    ("Paystack MFB", "51457", "paystack-mfb-ng", "nuban"),
    ("Paystack-Titan", "100039", "titan-paystack", "nuban"),
    ("Peace Microfinance Bank", "50743", "peace-microfinance-bank-ng", "nuban"),
    ("PECANTRUST MICROFINANCE BANK LIMITED", "51226", "pecantrust-microfinance-bank-limited-ng", "nuban"),
    ("Personal Trust MFB", "51146", "personal-trust-mfb-ng", "nuban"),
    ("Petra Mircofinance Bank Plc", "50746", "petra-microfinance-bank-plc", "nuban"),
    ("Pettysave MFB", "MFB51452", "pettysave-mfb-ng", "nuban"),
    ("PFI FINANCE COMPANY LIMITED", "050021", "pfi-finance-company-limited-ng", "nuban"),
    ("Platinum Mortgage Bank", "268", "platinum-mortgage-bank-ng", "nuban"),
    ("Pocket App", "00716", "pocket", "nuban"),
    ("Polaris Bank", "076", "polaris-bank", "nuban"),
    ("Polyunwana MFB", "50864", "polyunwana-mfb-ng", "nuban"),
    ("PremiumTrust Bank", "105", "premiumtrust-bank-ng", "nuban"),
    ("Prospa Capital Microfinance Bank", "50739", "prospa-capital-microfinance-bank-ng", "nuban"),
    ("PROSPERIS FINANCE LIMITED", "050023", "prosperis-finance-limited-ng", "nuban"),
    ("Providus Bank", "101", "providus-bank", "nuban"),
    ("QuickFund MFB", "51293", "quickfund-mfb", "nuban"),
    ("Rand Merchant Bank", "502", "rand-merchant-bank", "nuban"),
    ("RANDALPHA MICROFINANCE BANK", "090496", "randalpha-microfinance-bank-ng", "nuban"),
    ("Rank MFB", "50130", "rank-mfb-ng", "nuban"),
    ("Refuge Mortgage Bank", "90067", "refuge-mortgage-bank", "nuban"),
    ("REHOBOTH MICROFINANCE BANK", "50761", "rehoboth-microfinance-bank-ng", "nuban"),
    ("RenMoney Microfinance Bank", "51049", "renmoney-microfinance-bank-ng", "nuban"),
    ("Rephidim Microfinance Bank", "50994", "rephidim", "nuban"),
    ("Retrust Mfb", "51375", "retrust-mfb-ng", "nuban"),
    ("Rex Microfinance Bank", "51108", "rex-microfinance-bank-ng", "nuban"),
    ("Rigo Microfinance Bank Limited", "51286", "rigo-microfinance-bank-limited-ng", "nuban"),
    ("ROCKSHIELD MICROFINANCE BANK", "50767", "rockshield-microfinance-bank-ng", "nuban"),
    ("RSU MICROFINANCE BANK", "50622", "rsu-microfinance-bank-ng", "nuban"),
    ("Rubies MFB", "125", "rubies-mfb", "nuban"),
    ("Safe Haven MFB", "51113", "safe-haven-mfb-ng", "nuban"),
    ("SAGE GREY FINANCE LIMITED", "40165", "sage-grey-finance-limited-ng", "nuban"),
    ("Shield MFB", "50582", "shield-mfb-ng", "nuban"),
    ("Signature Bank Ltd", "106", "signature-bank-ltd-ng", "nuban"),
    ("Solid Allianze MFB", "51062", "solid-allianze-mfb", "nuban"),
    ("Solid Rock MFB", "50800", "solid-rock-mfb", "nuban"),
    ("SOURCE MFB", "90641", "source-mfb-ng", "nuban"),
    ("Sparkle Microfinance Bank", "51310", "sparkle-microfinance-bank", "nuban"),
    ("SPECTRUM MFB LTD", "50756", "spectrum-mfb-ltd-ng", "nuban"),
    ("Springfield Microfinance Bank", "51429", "springfield-microfinance-bank-ng", "nuban"),
    ("Stanbic IBTC Bank", "221", "stanbic-ibtc-bank", "nuban"),
    ("Standard Chartered Bank", "068", "standard-chartered-bank", "nuban"),
    ("STANFORD MICROFINANCE BANK", "090162", "stanford-microfinance-bank-ng", "nuban"),
    ("STATESIDE MICROFINANCE BANK", "50809", "stateside-microfinance-bank-ng", "nuban"),
    ("STB Mortgage Bank", "070022", "stb-mortgage-bank-ng", "nuban"),
    ("Stellas MFB", "51253", "stellas-mfb", "nuban"),
    ("Sterling Bank", "232", "sterling-bank", "nuban"),
    ("Summit Bank", "00305", "summit-bank-ng", "nuban"),
    ("Suntrust Bank", "100", "suntrust-bank", "nuban"),
    ("Supreme MFB", "50968", "supreme-mfb-ng", "nuban"),
    ("Sycamore Microfinance Bank", "51056", "sycamore-microfinance-bank-ng", "nuban"),
    ("TAJ Bank", "302", "taj-bank", "nuban"),
    ("Tangerine Money", "51269", "tangerine-money", "nuban"),
    ("Tatum Bank", "109", "tatum-bank-ng", "nuban"),
    ("Tatum Bank Ltd", "00109", "tatum-bank-ltd-ng", "nuban"),
    ("TENN", "51403", "tenn-ng", "nuban"),
    ("Think Finance Microfinance Bank", "677", "think-finance-microfinance-bank-ng", "nuban"),
    ("Titan Bank", "102", "titan-bank", "nuban"),
    ("TOPRATE MFB", "90801", "toprate-mfb-ng", "nuban"),
    ("TransPay MFB", "090708", "transpay-mfb-ng", "nuban"),
    ("TRUSTBANC J6 MICROFINANCE BANK", "51118", "trustbanc-j6-microfinance-bank-ng", "nuban"),
    ("U and C MFB", "50840", "u-and-c-mfb-ng", "nuban"),
    ("U&C Microfinance Bank Ltd (U AND C MFB)", "50840", "uc-microfinance-bank-ltd-u-and-c-mfb-ng", "nuban"),
    ("UBJ Microfinance Bank Limited", "51396", "ubj-microfinance-bank-limited-ng", "nuban"),
    ("UCEE MFB", "090706", "ucee-mfb-ng", "nuban"),
    ("Uhuru MFB", "51322", "uhuru-mfb-ng", "nuban"),
    ("Ultraviolet Microfinance Bank", "51080", "ultraviolet-microfinance-bank-ng", "nuban"),
    ("Umunnachi Microfinance Bank Ltd", "51097", "umunnachi-microfinance-bank-ltd-ng", "nuban"),
    ("Unaab Microfinance Bank Limited", "50870", "unaab-microfinance-bank-limited-ng", "nuban"),
    ("UNIABUJA MFB", "51447", "uniabuja-mfb", "nuban"),
    ("Unical MFB", "50871", "unical-mfb", "nuban"),
    ("Unilag Microfinance Bank", "51316", "unilag-microfinance-bank-ng", "nuban"),
    ("UNIMAID MICROFINANCE BANK", "50875", "unimaid-microfinance-bank-ng", "nuban"),
    ("Union Bank of Nigeria", "032", "union-bank-of-nigeria", "nuban"),
    ("United Bank For Africa", "033", "united-bank-for-africa", "nuban"),
    ("Unity Bank", "215", "unity-bank", "nuban"),
    ("UNIUYO Microfinance Bank Ltd", "50880", "uniuyo-microfinance-bank-ltd-ng", "nuban"),
    (
        "Uzondu Microfinance Bank Awka Anambra State",
        "50894",
        "uzondu-microfinance-bank-awka-anambra-state-ng",
        "nuban",
    ),
    ("Vale Finance Limited", "050020", "vale-finance", "nuban"),
    ("VFD Microfinance Bank Limited", "566", "vfd", "nuban"),
    ("Victory MFB", "51085", "victory-mfb-ng", "nuban"),
    ("VISTA MFB", "90787", "vista-mfb-ng", "nuban"),
    ("Visual ICT Limited (TagPay)", "100023", "visual-ict-limited-tagpay-ng", "nuban"),
    ("Waya Microfinance Bank", "51355", "waya-microfinance-bank-ng", "nuban"),
    ("Wema Bank", "035", "wema-bank", "nuban"),
    ("Weston Charis MFB", "51386", "weston-charis-mfb-ng", "nuban"),
    ("Whitecrust Finance Company", "402001", "whitecrust-finance-company-ng", "nuban"),
    ("Xpress Wallet", "100040", "xpress-wallet-ng", "nuban"),
    ("YCT MFB", "51253", "yct-mfb-ng", "nuban"),
    ("Yes MFB", "594", "yes-mfb-ng", "nuban"),
    ("Zap", "00zap", "zap", "nuban"),
    ("Zenith Bank", "057", "zenith-bank", "nuban"),
    ("Zitra MFB", "51373", "zitra-mfb-ng", "nuban"),
)
