# Generated by Django 6.1.1 on 2026-10-06 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0002_chat_connectors"),
    ]

    operations = [
        migrations.CreateModel(
            name="Context",
            fields=[
                (
                    "chat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="pact",
                        serialize=False,
                        to="chat.chat",
                    ),
                ),
                ("brand", models.CharField(max_length=64)),
                ("owner", models.CharField(db_index=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.CharField(max_length=200)),
                ("message", models.JSONField(null=True)),
                (
                    "context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="pact.context",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("context", "message_id"), name="one_reply_per_message"
                    )
                ],
            },
        ),
    ]
